### PR TITLE
Assert Heap Size 

### PR DESCRIPTION
**Pull request by yogh333**

### CODE REVIEW

**Comment by emmanuelm41** [comment]
Hey @yogh333! Any reason why this check was added? It is quite inconvenient in cases where there is a limited size between stack and heap. Between 8192, and 16384 there is a big gap, and could potentially block apps where the stack is important too.

**Comment by emmanuelm41** [comment]
Particularly, this could break the Ironfish DKG app that we are currently reviewing on ledger side.

**Comment by emmanuelm41** [comment]
This [PR](https://github.com/LedgerHQ/ledger-device-rust-sdk/pull/208/files) increases the stack usage on 359 bytes (because of the warning icon), and that breaks our app. We cannot decrease the heap size a bit, and 8192 is not enough. :/

**Comment by yogh333** [comment]
@emmanuelm41 You are right, I have modified the assert in this PR #209

**Comment by emmanuelm41** [comment]
@yogh333 thanks a lot for the quick fix. I think it will work now!! Again, thanks!

**Pull request merged**
